### PR TITLE
fix: deadlock on task queue

### PR DESCRIPTION
**Pull request by hjanetzek**
When the scene gets disposed as a main-loop task it hanged while enqueueing its textures for disposal

### CODE REVIEW

**Comment by tallytalwar** [comment]
This looks good, should fix scene reloading I guess. Will also test on my scene switcher demo app.

**Comment by karimnaaji** [comment]
Looks good to me, scene reloading fix would need more work, there's still a crash happening.

**Comment by tallytalwar** [comment]
2 things:

- Branch name does not make sense :|
- There is a crash when the main threads deletes a tile and tileWorker calls `complete` on this tile. There should be some sync between the two.

**Comment by karimnaaji** [comment]
On main thread:
```
(lldb) bt
* thread #1: tid = 0x52d37, 0x0000000100056f73 tangram`Tangram::RasterTileTask::complete() [inlined] std::__1::vector<Tangram::Raster, std::__1::allocator<Tangram::Raster> >::push_back(this=0x00000000000000a8 size=0, __x=0x00007fff5fbfc880) at vector:1606, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xb0)
  * frame #0: 0x0000000100056f73 tangram`Tangram::RasterTileTask::complete() [inlined] std::__1::vector<Tangram::Raster, std::__1::allocator<Tangram::Raster> >::push_back(this=0x00000000000000a8 size=0, __x=0x00007fff5fbfc880) at vector:1606
    frame #1: 0x0000000100056f73 tangram`Tangram::RasterTileTask::complete(this=0x00006000001414b8) + 307 at rasterSource.cpp:53
    frame #2: 0x00000001002d7778 tangram`Tangram::TileManager::updateTileSet(this=0x00006180001400b0, _tileSet=0x0000608000160480, _view=0x00007fff5fbfea08, _visibleTiles=size=16) + 1304 at tileManager.cpp:159
    frame #3: 0x00000001002d6da0 tangram`Tangram::TileManager::updateTileSets(this=0x00006180001400b0, _view=0x00007fff5fbfea08, _visibleTiles=size=16) + 912 at tileManager.cpp:123
    frame #4: 0x00000001002a6cdd tangram`Tangram::update(_dt=0.130316779) + 2173 at tangram.cpp:215
    frame #5: 0x00000001000077e0 tangram`main(argc=1, argv=0x00007fff5fbff1d8) + 1392 at main.cpp:362
    frame #6: 0x00007fff8a9625ad libdyld.dylib`start + 1
    frame #7: 0x00007fff8a9625ad libdyld.dylib`start + 1
```

When raster tile task is complete, `m_tile` gets assigned a `nullptr` as @tallytalwar mentioned.

**Comment by hjanetzek** [comment]
@tallytalwar the bug was older but became critical with the raster-source branch. so naming it fix-deadlock-on-taskqueue next time.

The crash above seems to be unrelated to this change https://github.com/tangrams/tangram-es/pull/727

**Pull request merged**
