### PR TITLE
Debug text tile infos

### PR DESCRIPTION
**Pull request by karimnaaji**
Add a way to display some tile debug infos with text, defaulting to tile ids but could be any tile informations (loading time, number of labels...)

screen shot 2015-04-15 at 4 55 09 pm

### CODE REVIEW

**Comment by blair1618** [comment]
Looks good! Small question: on my machine the tile info labels aren't centered, the left edge of the labels are in the center of the tile. Are labels always anchored by one of their left corners?

**Comment by tallytalwar** [comment]
I believe thats true (at least what Karim told me last). He can confirm.

**Comment by karimnaaji** [comment]
Yes! it's anchored by lower left corner, it's misleading because the image comes from some test on the upcoming logic on label-occlusion branch where text are centered.

**Comment by karimnaaji** [comment]
I'm planning on making a configurable anchor point anyway

**Pull request merged**
