### PR TITLE
use indices for glyphs verts

### PR DESCRIPTION
**Pull request by karimnaaji**
use indices for glyph verts, based on #232

### CODE REVIEW

**Comment by hjanetzek** [comment]
Yes, using indices was also my plan - I'm working on a patch to use one shared vbo for quad indices for all LabelMeshes

**Comment by karimnaaji** [comment]
Coo! I wonder how it would work without resizing the meshes?

**Comment by hjanetzek** [comment]
I would make the indices buffer as large as is reasonable to batch quads for one draw call. Then advance the vertex pointer and draw the same indices twice (or more times) when there are vertices left. This requires to override the VboMesh::draw call to not advance the indices

2^16 / 4 * 6 would be the maximum vertices to draw with one call (= 16384 quads) - I think one does not loose much when making it half of the size.

**Comment by karimnaaji** [comment]
Makes sense, I think moving the vertex pointer would most likely not happen so often since it lets a pretty good quad budget.

**Pull request closed without merging**
