### PR TITLE
fix label offset

### PR DESCRIPTION
**Pull request by hjanetzek**

### CODE REVIEW

**Comment by tallytalwar** [comment]
LGTM

**Comment by blair1618** [comment]
So an offset was being applied with the opposite sign in 'y'?

**Comment by hjanetzek** [comment]
It was my refactoring from using angles to direction vectors which introduced the issue. I've missed to check the docs - while testing offset parameters positive y-up seemed too natural to me..

**Comment by hjanetzek** [comment]
don't merge yet! now need to fix offset with line labels

**Comment by blair1618** [comment]
Oh yeah, interesting. I think the scene syntax is inconsistent about y-direction in some places :(

**Comment by hjanetzek** [comment]
Now it should be correct. In this case it's probably us having too many different y-axis orientations..

**Pull request merged**
