### PR TITLE
Deploy Android snapshots to Artifactory at oss.jfrog.org

### PR DESCRIPTION
**Pull request by matteblair**
This is a work-in-progress, not ready for merging yet. The branch needs to have an open PR to test the CI process.

Reference links:
 - https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org
 - https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin
 - https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory
 - https://github.com/JFrogDev/project-examples/tree/master/gradle-examples
 - https://github.com/google/volley

Deployment links:
 - https://bintray.com/tangrams/maven/tangram
 - https://oss.jfrog.org/artifactory/webapp/#/builds/tangram-android
 - https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/simple/General/oss-snapshot-local/com/mapzen/tangram/tangram/

### CODE REVIEW

**Comment by matteblair** [comment]
Status update as I'm discovering more about how these services work and don't work:

While Bintray works just fine with pretty much any files that you want to host and distribute, oss.jfrog.org is much pickier about what it will host. In particular, OJO seems to only want to host Maven-compatible artifacts. Our android artifacts are definitely Maven-compatible so those have no issues, but the cocoapods snapshots that I'd been hoping to host on OJO appear to not be Maven-compatible. I'm not 100% clear on what makes something Maven-compatible, but depending on the name of the cocoapods archive when I upload it to OJO, it is sometimes accepted and sometimes rejected "due to conflict in the snapshot release handling policy". 

I think a reasonable next step here is for Android: snapshots on OJO and releases on Bintray; for iOS: only host releases on Bintray and continue evaluating whether snapshot hosting is actually needed. I'm not sure exactly how snapshots would be used in cocoapods, or whether downstream users would want them. I'm not sure how often snapshots are used on Android either, for that matter. For iOS it's certain that the most important thing for consumers is to have a current, reliable source for release downloads, so I won't delay that further by continuing to fight against OJO :P

**Comment by tallytalwar** [comment]
Pinging @msmollin here for usage of snapshots in iOS development process.

I am in agreement of pushing release to bintray first and get the current developers get going. We can evaluate snapshots strategies for iOS later.

**Comment by msmollin** [comment]
I would just worry about being able to have both debug and release variants of "released" iOS artifacts in bintray and that will be good enough for v1. I can't recall ever needing a snapshot available via cocoapods. It might have made things easier in some scenarios for testing but it wasn't arduous to build a local snapshot in those cases.

**Comment by matteblair** [comment]
Closing in favor of #1789

**Pull request closed without merging**
