### PR TITLE
More gentle proxy tile depth adjustment

### PR DESCRIPTION
**Pull request by blair1618**
To address https://github.com/tangrams/tangram-es/issues/377

### CODE REVIEW

**Comment by tallytalwar** [comment]
This seems to behave mostly right.

We saw a this case, when all the children tile of a proxy parent are loaded, there is a flash of proxy parent shown before all children (visible) get displayed.

Its weird because proxy tile should never be thrown on top of the visible tiles, which is happening here.

**Comment by hjanetzek** [comment]
I think another visible interference happens when a distant tile is not a proxy, but the near tiles are proxies

**Comment by tallytalwar** [comment]
Hannes Shouldn't tile sorting make sure that near tiles are loaded first.
That will avoid this issue.

**Comment by hjanetzek** [comment]
I mean e.g. the case where the view is tilted and shows only non-proxy tiles, then when zooming out the near tiles switch to a lower zoom-level first (or maybe only the near tiles) and use the previous tiles as proxies while the distant tiles are still on the old zoom-level. Then you have near tiles that use proxies while distant tiles are shown in front. 
Another case where this may happen is when the distant tiles are cached but the near ones aren't

**Comment by blair1618** [comment]
Yes, I think this has been happening in tilted views - it looks pretty odd when it happens. 

I believe that should be fixed with this change. The depth adjustment that proxy geometry gets is so small that it should no longer impact geometries that are actually separated in 3d space.

**Comment by hjanetzek** [comment]
@tallytalwar wouldn't the proxy tile commit better fit into the tilemanager-tweaks branch?

**Comment by tallytalwar** [comment]
@hjanetzek It was fixing, something were seeing for proxy so I added it over here.

Also I did not notice the tilemanager tweak PR (I think it was named something else before).

**Pull request merged**
