### PR TITLE
Scene load timing

### PR DESCRIPTION
**Pull request by hjanetzek**
Testing bubble-wrap yaml loading from before ~180ms it's now down to ~20ms :)

```
...
TANGRAM sceneLoading.cpp:50: loadTime 179.856995
TANGRAM sceneLoading.cpp:50: loadTime 178.826004
TANGRAM sceneLoading.cpp:50: loadTime 178.352997
TANGRAM sceneLoading.cpp:50: loadTime 172.988998
TANGRAM sceneLoading.cpp:50: loadTime 170.507004
TANGRAM sceneLoading.cpp:50: loadTime 170.852005
TANGRAM sceneLoading.cpp:50: loadTime 170.376999
TANGRAM sceneLoading.cpp:50: loadTime 175.672989
TANGRAM sceneLoading.cpp:50: loadTime 170.598007
TANGRAM sceneLoading.cpp:50: loadTime 171.723999
TANGRAM sceneLoading.cpp:50: loadTime 169.934998
SceneLoadingFixture/BuildTest         206554937  206666333          3                                 
SceneLoadingFixture/BuildTest         190120140  190000000          3                                 
SceneLoadingFixture/BuildTest         191296854  191111333          3                                 
SceneLoadingFixture/BuildTest         189437208  188889000          3                                 
SceneLoadingFixture/BuildTest         190895411  191110667          3                                 
SceneLoadingFixture/BuildTest         187417874  186666333          3                                 
SceneLoadingFixture/BuildTest         189427798  190000333          3                                 
SceneLoadingFixture/BuildTest         184864348  184444333          3                                 
SceneLoadingFixture/BuildTest         183145575  183333333          3                                 
SceneLoadingFixture/BuildTest         181458549  181111000          3                                 
SceneLoadingFixture/BuildTest_mean    189461870  189333267          3                                 
SceneLoadingFixture/BuildTest_stddev    6536774    6651780          0    
```

```
...
TANGRAM sceneLoading.cpp:50: loadTime 17.571001
TANGRAM sceneLoading.cpp:50: loadTime 19.980000
TANGRAM sceneLoading.cpp:50: loadTime 20.019001
TANGRAM sceneLoading.cpp:50: loadTime 20.024000
TANGRAM sceneLoading.cpp:50: loadTime 17.777000
TANGRAM sceneLoading.cpp:50: loadTime 20.177000
TANGRAM sceneLoading.cpp:50: loadTime 20.146999
SceneLoadingFixture/BuildTest          26122273   26133360         25                                 
SceneLoadingFixture/BuildTest          22967413   22933360         25                                 
SceneLoadingFixture/BuildTest          23093346   23199960         25                                 
SceneLoadingFixture/BuildTest          22734185   22666680         25                                 
SceneLoadingFixture/BuildTest          23815959   23866640         25                                 
SceneLoadingFixture/BuildTest          23048667   23066680         25                                 
SceneLoadingFixture/BuildTest          23597101   23600000         25                                 
SceneLoadingFixture/BuildTest          23040539   22933320         25                                 
SceneLoadingFixture/BuildTest          22584969   22666680         25                                 
SceneLoadingFixture/BuildTest          22013293   22000000         25                                 
SceneLoadingFixture/BuildTest_mean     23301775   23306668         25                                 
SceneLoadingFixture/BuildTest_stddev    1053115    1061324          0  
```

### CODE REVIEW

**Comment by hjanetzek** [comment]
Also interesting: 
shot-2016-11-30_12-09-45
shot-2016-11-30_12-09-36

It's also 30MB allocations just for the temporary `vector<RegExp<vector<RegExp>...>>` that are now statically compiled.

(the leak is not accurate - probably wrong guess by heaptrak)

**Comment by tallytalwar** [comment]
This is some great work @hjanetzek. Many congrats.

**Comment by hjanetzek** [comment]
5X Speedup for bubble-wrap on RPI2 with `-O3 -march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard`

```
[alarm@alarmpi][~/tangram-es/build/perf/bin]% perf record -g ./bench/sceneLoading.out --benchmark_repetitions=10                                              
Run on (4 X 38.4 MHz CPU s)
2016-12-03 11:12:32
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incure extra overhead.
Benchmark                              Time(ns)    CPU(ns) Iterations
---------------------------------------------------------------------
TANGRAM sceneLoading.cpp:62: loadTime 1068.529053
TANGRAM sceneLoading.cpp:62: loadTime 984.297974
TANGRAM sceneLoading.cpp:62: loadTime 952.078979
TANGRAM sceneLoading.cpp:62: loadTime 933.009033
TANGRAM sceneLoading.cpp:62: loadTime 932.663025
TANGRAM sceneLoading.cpp:62: loadTime 950.906982
TANGRAM sceneLoading.cpp:62: loadTime 931.657043
TANGRAM sceneLoading.cpp:62: loadTime 950.534973
TANGRAM sceneLoading.cpp:62: loadTime 980.055969
TANGRAM sceneLoading.cpp:62: loadTime 952.934021
SceneLoadingFixture/BuildTest        1069365067 1070000000          1                                 
SceneLoadingFixture/BuildTest         984817627  990000000          1                                 
SceneLoadingFixture/BuildTest         952600315  960000000          1                                 
SceneLoadingFixture/BuildTest         933554677  940000000          1                                 
SceneLoadingFixture/BuildTest         933152960  930000000          1                                 
SceneLoadingFixture/BuildTest         951450479  950000000          1                                 
SceneLoadingFixture/BuildTest         932166665  930000000          1                                 
SceneLoadingFixture/BuildTest         951099075  950000000          1                                 
SceneLoadingFixture/BuildTest         980568021  980000000          1                                 
SceneLoadingFixture/BuildTest         953380463  950000000          1                                 
SceneLoadingFixture/BuildTest_mean    964215535  965000000          1                                 
SceneLoadingFixture/BuildTest_stddev   39073874   39560081          0   
```

```
[alarm@alarmpi][~/tangram-es/build/perf/bin]% perf record -g ./bench/sceneLoading.out --benchmark_repetitions=10
Run on (4 X 38.4 MHz CPU s)
2016-12-03 10:50:38
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incure extra overhead.
Benchmark                              Time(ns)    CPU(ns) Iterations
---------------------------------------------------------------------
TANGRAM sceneLoading.cpp:62: loadTime 230.207001
TANGRAM sceneLoading.cpp:62: loadTime 182.033997
TANGRAM sceneLoading.cpp:62: loadTime 184.563004
TANGRAM sceneLoading.cpp:62: loadTime 184.056992
TANGRAM sceneLoading.cpp:62: loadTime 180.577988
TANGRAM sceneLoading.cpp:62: loadTime 180.672012
TANGRAM sceneLoading.cpp:62: loadTime 180.738998
TANGRAM sceneLoading.cpp:62: loadTime 177.201004
TANGRAM sceneLoading.cpp:62: loadTime 181.550995
TANGRAM sceneLoading.cpp:62: loadTime 177.639999
TANGRAM sceneLoading.cpp:62: loadTime 181.535004
TANGRAM sceneLoading.cpp:62: loadTime 186.182007
TANGRAM sceneLoading.cpp:62: loadTime 182.478989
TANGRAM sceneLoading.cpp:62: loadTime 180.490997
TANGRAM sceneLoading.cpp:62: loadTime 180.634003
TANGRAM sceneLoading.cpp:62: loadTime 180.535995
TANGRAM sceneLoading.cpp:62: loadTime 180.054001
TANGRAM sceneLoading.cpp:62: loadTime 182.007996
TANGRAM sceneLoading.cpp:62: loadTime 182.476990
TANGRAM sceneLoading.cpp:62: loadTime 181.718002
TANGRAM sceneLoading.cpp:62: loadTime 181.721008
TANGRAM sceneLoading.cpp:62: loadTime 180.699997
TANGRAM sceneLoading.cpp:62: loadTime 181.505997
TANGRAM sceneLoading.cpp:62: loadTime 182.508011
TANGRAM sceneLoading.cpp:62: loadTime 182.311005
TANGRAM sceneLoading.cpp:62: loadTime 180.125000
TANGRAM sceneLoading.cpp:62: loadTime 180.919998
TANGRAM sceneLoading.cpp:62: loadTime 180.901001
TANGRAM sceneLoading.cpp:62: loadTime 184.026001
TANGRAM sceneLoading.cpp:62: loadTime 182.239990
TANGRAM sceneLoading.cpp:62: loadTime 182.944000
SceneLoadingFixture/BuildTest         183788715  183333333          3                                 
SceneLoadingFixture/BuildTest         180907768  180000000          3                                 
SceneLoadingFixture/BuildTest         179047974  180000000          3                                 
SceneLoadingFixture/BuildTest         183633040  183333333          3                                 
SceneLoadingFixture/BuildTest         180826796  180000000          3                                 
SceneLoadingFixture/BuildTest         181759861  180000000          3                                 
SceneLoadingFixture/BuildTest         181610418  180000000          3                                 
SceneLoadingFixture/BuildTest         182440620  183333333          3                                 
SceneLoadingFixture/BuildTest         180842334  183333333          3                                 
SceneLoadingFixture/BuildTest         183339293  183333333          3                                 
SceneLoadingFixture/BuildTest_mean    181819682  181666667          3                                 
SceneLoadingFixture/BuildTest_stddev    1426972    1666667          0   
```

**Comment by matteblair** [comment]
Is this PR still needed? I think the benchmark is the only part that's not in master yet.

**Comment by hjanetzek** [comment]
No - Reopening when I get back to reduce scene load time

**Pull request closed without merging**
