### PR TITLE
Locks to synchronize write for m_store

### PR DESCRIPTION
**Pull request by tallytalwar**
Fixes: https://github.com/tangrams/tangram-es/issues/404

### CODE REVIEW

**Comment by tallytalwar** [comment]
This should fix #404. @blair1618 can you try eraser-map with this. I was not able to make it crash in my testing. Thanks

**Comment by tallytalwar** [comment]
Hold on this. Found an async read!!

**Comment by blair1618** [comment]
Sure. Ping when you want me to test.

**Comment by tallytalwar** [comment]
This should be good now. 

However, had to make `DataSource::parse` non-const, so as to allow `ClientDataSource::parse` to lock `m_storeMutex`. Could not think of a better solution, to avoid this, at the moment.

**Comment by tallytalwar** [comment]
WOW! Herb Sutter for help: https://channel9.msdn.com/posts/C-and-Beyond-2012-Herb-Sutter-You-dont-know-blank-and-blank

WIll rebase with a better way of handling synchronous read on `m_store`.

**Pull request merged**
