### PR TITLE
Cleanup update loop

### PR DESCRIPTION
**Pull request by karimnaaji**
Clean update loop of `tangram.cpp`

### CODE REVIEW

**Comment by hjanetzek** [comment]
The updateVisibleTiles() doesn't really fit in the area of responsibility of TileManager imo.  (Other than that this commit is rebased and included in my label-refactoring branch)

**Comment by karimnaaji** [comment]
Well.. It doesn't seem like an overwhelming area of responsibility to extend it to.

**Comment by hjanetzek** [comment]
Sure, but I would still argue that it doesn't really fit into it :) 

Consider its current external interface updateTileSet() and getVisibileTiles() - It's sole responsibility is to provide tiles for rendering (and doing a lot of work internally to achieve this). 

Then what the proposed updateVisibleTiles actually does is to updateModelMatricesOfVisibleTilesRelativeToCurrentView() - To me this sounds more like a part of the general update/render loop than anything related to the tile managers work. From the call it is also not clear that the View is used to update the tiles.

**Comment by karimnaaji** [comment]
Merged in #219

**Pull request closed without merging**
