### PR TITLE
Fix shader undef injection

### PR DESCRIPTION
**Pull request by hjanetzek**
Plus nicer debug logs, like
```
ERROR shaderProgram.cpp:228: Shader compilation failed {style:elevation-color-contours}

Error line 460: 0(460) : error C1068: too much data in type constructor
455: 
456:     // Modify color before lighting is applied
457:     #pragma tangram: color
458: color = mix(vec4(CONTOURS_BACKGROUND_COLOR,CONTOURS_BACKGROUND_ALPHA),
459:             vec4(CONTOURS_COLOR,CONTOURS_ALPHA),
460:             aastep( dot(normal, vec3(0.,0.,1.)),
461:                     abs(sin((normal_elv_raster.a*PI)*CONTOURS_SCALE+CONTOURS_OFFSET)) ) );
462: 
463:     #if defined(TANGRAM_LIGHTING_FRAGMENT)
464:         color = calculateLighting(v_position.xyz, normal, color);
```

### CODE REVIEW

**Comment by tallytalwar** [comment]
Interesting we have not used a shader define like this until now to catch this bug!

**Comment by hjanetzek** [comment]
you know @patriciogonzalezvivo shaders :) it's extensively used in tangram-blocks

**Comment by patriciogonzalezvivo** [comment]
gentelmens, is always my pleasure to serve to the cause : )

**Comment by blair1618** [comment]
LGTM!

**Pull request merged**
