### PR TITLE
Floating Point comparison fix in filter equality

### PR DESCRIPTION
**Pull request by tallytalwar**
We should still do this along with the fixes from https://github.com/tangrams/tangram-es/pull/431.

### CODE REVIEW

**Comment by blair1618** [comment]
Sure, but let's put the simple equality check first so we can skip the epsilon check if it isn't needed.

**Comment by tallytalwar** [comment]
Good call, covered by a179272

**Comment by blair1618** [comment]
Think you can squash these and remove that extra space before "v" on line 41? Thanks :)

**Comment by tallytalwar** [comment]
Ha sure. Had already squashed.

**Pull request merged**
