### PR TITLE
Rpi ncr

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
Non-continuos rendering (single thread)

### CODE REVIEW

**Comment by blair1618** [comment]
The re-organization here seems like a good thing, we should keep that. However the "non-continuous rendering" implemented here is unfortunately not super useful :\ 

The CPU won't be doing any less work, it'll just be running through a while loop for all the cycles that it would have otherwise been working on rendering. To get any actual efficiency improvements we'll need to actually put the rendering thread to sleep and wake it again when input or network events require a re-render. Various event-loop libraries can do this, as well as the very low-level pthread interface.

**Comment by patriciogonzalezvivo** [comment]
I see. I will review and go back to the research

**Comment by blair1618** [comment]
If you're happy with the re-organization changes we can go ahead and merge those. Adding truly event-driven rendering can be another PR since it'll be another substantial change.

**Comment by patriciogonzalezvivo** [comment]
that sound great

**Comment by blair1618** [comment]
Will do! I may have mentioned it before, but SDL may be useful for when you revisit this. I think it's cool how far the RPi implementation has gone without using external dependencies, but using SDL for our implementation here would be a good demonstration to users of how to use Tangram with another very popular cross-platform framework.

**Pull request merged**
