### PR TITLE
Use milliseconds for duration in Marker setPointEased

### PR DESCRIPTION
**Pull request by matteblair**
Resolves https://github.com/tangrams/tangram-es/issues/1264

### CODE REVIEW

**Comment by matteblair** [comment]
@tallytalwar The iOS interface appears to be consistent here, it uses seconds for all durations. Apple's UIKit animations use seconds as well, so I think this is the right choice.

**Comment by matteblair** [comment]
I will, however, change the name of the 'duration' parameters in TGMapViewController, to clarify the units.

**Comment by karimnaaji** [comment]
@tallytalwar updated the param name to `seconds` in #1290 .

**Comment by tallytalwar** [comment]
Need to rebase and resolve conflicts, good to go when done.

**Pull request merged**
