### PR TITLE
Data source configurations can specify url parameters

### PR DESCRIPTION
**Pull request by blair1618**
Resolves https://github.com/tangrams/tangram-es/issues/663

### CODE REVIEW

**Comment by bcamper** [comment]
URL params need to be inserted *after* the base URL, but *before* the `#` (if one is already present in the URL), and take into account possibly existing parameters:

Examples where `url_params: { a: 1, b: 2 }`:

- `http://baseurl.com/` => `http://baseurl.com/?a=1&b=2`
- `http://baseurl.com/?c=3&d=4` => `http://baseurl.com/?c=3&d=4&a=1&b=2`
- `http://baseurl.com/#lat/lng/z` => `http://baseurl.com/?a=1&b=2#lat/lng/z`
- `http://baseurl.com/?c=3&d=4#lat/lng/z` => `http://baseurl.com/?c=3&d=4&a=1&b=2#lat/lng/z`

See https://github.com/tangrams/tangram/pull/204/files#diff-be73193a7de1c86c1903f5cf92321d2aR84.

**Comment by blair1618** [comment]
Huh, well I hadn't foreseen that someone would use a hash in a data source URL but I guess it's not impossible. I'll update. 

Just to check: trailing ampersands and duplicated parameters are generally permissible, yes?

**Comment by bcamper** [comment]
Using a hash in a URL data source template is unlikely but valid, so I think it should not break.

Trailing ampersands shouldn't be a problem as far as I know, and duplicated parameters I explicitly punted on for the JS implementation because it's not rational to put in both the template and the `url_params`, and can be avoided by the scene file author.

**Comment by blair1618** [comment]
Updated! I was tempted to make a new utility file for URL functions, but I'm trying to be diligent about not abstracting anything until I use it in at least two places.

**Pull request merged**
