### PR TITLE
Invalidate render state tracking of current texture binding

### PR DESCRIPTION
**Pull request by karimnaaji**
#777

### CODE REVIEW

**Comment by blair1618** [comment]
Ah now I understand the problem this aims to fix :)

This looks correct. We could be slightly more efficient if we really wanted to by caching texture bindings as pairs of (unit, texture).

**Comment by karimnaaji** [comment]
It's ok to store them separately, storing them as a pair `<unit,texture>` would make it discard transition `<0, 1>` to `<0, 2>` where only the texture binding should be updated.

**Comment by blair1618** [comment]
What I mean is that if our state goes from (unit: 0, texture: 1) to (unit: 1, texture: 2), texture 1 is still bound to unit 0, so if we make 0 our active unit again we don't have to re-bind texture 1.

**Comment by blair1618** [comment]
But this LGTM as-is and we can consider further refinement in the future as-needed.

**Comment by karimnaaji** [comment]
Yes we can see the trace and see what's going on but I wonder if it's likely to happen in our context; styles most likely use next texture unit when previous one was not available for them since we always use the units starting from 0, but something to consider if we share gl-texture object between styles.

**Pull request merged**
