### PR TITLE
Tessfix

### PR DESCRIPTION
**Pull request by blair1618**
Fixes the crashes caused by libtess2 failing assertions when fed degenerate geometry:

I've added libtess2 as a submodule since it is 1. very small, and 2. usable without modification to source files. The only change to libtess2 we need is to compile with the preprocessor definition "NDEBUG", which disables all assertions. The effect of this is that tesselation output from degenerate geometry is technically undefined, but in practice the result is that there is no visible output for these geometries.

### CODE REVIEW

**Comment by blair1618** [comment]
Just realized that I still need to apply this change to the RPI build, we should wait until I've tested that to merge.

**Comment by blair1618** [comment]
Another thought that might not belong in this PR: We now have two libraries with source files in our "include" folder for the core project (jsoncpp and libtess2). Maybe we should move these to another folder like "3rdparty" or "deps" or something.

**Comment by tallytalwar** [comment]
+1 on moving jsoncpp and libtess2 to an appropriate directory.

**Comment by bcamper** [comment]
Sometimes called 'vendor', though that is also a kinda gross word. 'deps'
is probably better (or even dependencies, clearer and you're not gonna type
it that often).

**Comment by blair1618** [comment]
Ready for merge!

**Pull request merged**
