### PR TITLE
Load hardware max texture size

### PR DESCRIPTION
**Pull request by karimnaaji**
Related #516 
Instead of using a default value of 2048 (which is the most widely least supported texture size) load the hardware value.

### CODE REVIEW

**Comment by blair1618** [comment]
Cool, this makes sense as a feature. It seems very similar in nature to the GL extension code, do you think it would make sense to consolidate them into a class/namespace that queries device features?

**Comment by karimnaaji** [comment]
Yeah good call to reorganize this a bit.

**Comment by blair1618** [comment]
Lookin' good. Merging!

**Comment by czxczq521** [comment]
It's great.

**Pull request merged**
