### PR TITLE
scale text offset by pixelScale

### PR DESCRIPTION
**Pull request by hjanetzek**

### CODE REVIEW

**Comment by hjanetzek** [comment]
This fix is necessary to show both text- and sprite-labels of features in eraser-map when pixelScale > 1. See Williamsburg Bridge for example.

**Comment by blair1618** [comment]
Yeah this makes sense. 

@nvkelso this may address the regressions you were just pointing out to me.

**Comment by hjanetzek** [comment]
it's indeed a regression from pre-alfons :/

**Comment by hjanetzek** [comment]
Debug mode to show all labels that were added for a tile
shot-2016-03-21_22-16-02

**Comment by blair1618** [comment]
Oh boy the debug drawing looks fun haha

So this is all the labels in the buffer objects?

**Comment by hjanetzek** [comment]
@blair1618 that's what *was* hidden in the buffer objects. Now it's only the visible labels and the quadvertices for labels kept per tile are much smaller than the mesh buffer vertices

**Comment by blair1618** [comment]
Cool. LGTM.

**Pull request merged**
