### PR TITLE
Sceneloader refactoring

### PR DESCRIPTION
**Pull request by hjanetzek**
Continuing #300

### CODE REVIEW

**Comment by blair1618** [comment]
This is looking good! I think Varun is reviewing as well.

Much cleaner, thanks :)

**Comment by hjanetzek** [comment]
Thanks! 

Just saw that I introduced a small breakage while removing GL_ prefix from extensions..

**Comment by hjanetzek** [comment]
All changes that went in with the latest rebase https://gist.github.com/hjanetzek/4c62b45f4695ee326124

**Comment by tallytalwar** [comment]
@hjanetzek 
We also need to `Clone` the node when `propValue` is a `sequence` in `propMerge`.
https://github.com/tangrams/tangram-es/blob/sceneloader-refactoring/core/src/scene/sceneLoader.cpp#L527

**Comment by blair1618** [comment]
Looks like SDF multi-sampling is back on by default (https://github.com/tangrams/tangram-es/blob/sceneloader-refactoring/core/src/scene/sceneLoader.cpp#L766)

I had turned this off because it breaks font rendering on the Galaxy S3 (and probably others). We should fix this eventually, I just didn't want to worry about it for this launch.

**Comment by hjanetzek** [comment]
@tallytalwar @blair1618, changes are in. thanks! :)

**Comment by tallytalwar** [comment]
One small change and we are good with this:

Can we use yaml bool conversions here?

https://github.com/tangrams/tangram-es/blob/sceneloader-refactoring/core/src/scene/sceneLoader.cpp#L1019-L1022

**Comment by hjanetzek** [comment]
This case is a bit different as we 'steal' here two possible values that could be used for MatchEquality for the Existence filter, when we use yaml booleans here we could no check for things like building_part:yes/no OSM tags

**Comment by tallytalwar** [comment]
That's what we thought before, but based on the yaml 1.2 spec (
http://www.yaml.org/spec/1.2/spec.html#id2803629), it seems only
"true"/"True"/"TRUE" and respectively "false" values are legit.

"yes" or "no" will not be bool converted.

**Comment by hjanetzek** [comment]
ok, then we should also update yaml-cpp which still supports all 1.1 boolean tokens

**Comment by tallytalwar** [comment]
Ohh I thought yamlcpp is based on 1.2 spec and hence we went with it for
our parser.

If that is the case, then yes let's keep it like this for now and get
yamlcpp in place first.

**Comment by hjanetzek** [comment]
Yea. I'll do a follow up patch for this and yaml-cpp

**Comment by blair1618** [comment]
Oh that's awful. yaml-cpp claims to follow the 1.2 spec but you're totally right, it accepts the other boolean tokens D:

Let's fix that in our fork and submit a PR to the main repo (probably won't be merged for a long time, but I suppose it's the nice thing to do)

**Comment by bcamper** [comment]
ahhhhhhhhhhh

**Pull request merged**
