### PR TITLE
Planar triplanar mapping #537

### PR DESCRIPTION
**Pull request by karimnaaji**
#537

### CODE REVIEW

**Comment by tallytalwar** [comment]
LGTM

**Comment by blair1618** [comment]
@tallytalwar I don't think that the demo stylesheet changes here were intended to be merged. Can you revert that on master?

**Comment by karimnaaji** [comment]
Wait, this https://github.com/tangrams/tangram-es/commit/8ef3081f4c0d570a942abcd776d585af425b0482 was a drop commit.

**Comment by tallytalwar** [comment]
Ohh yes!! Will revert.

**Comment by tallytalwar** [comment]
@karimnaaji you want to remove the drop scene file here for a remerge?

**Comment by tallytalwar** [comment]
@karimnaaji ignore that!. Reverted that commit on master.

**Pull request merged**
