### PR TITLE
[rfc] simplify resources root handling

### PR DESCRIPTION
**Pull request by hjanetzek**
- either a path is relative, then bytesFromFile uses bundled resource path
- or a path is absolute then bytesFromFile just loads that file
- relative path replacements are all done in Scene Importer.

no more headaches, hopefully :)

PathType could also be removed, unless I'm missing something

### CODE REVIEW

**Comment by blair1618** [comment]
I believe you're right, now that we don't need to access any files bundled with the library itself (what used to be 'internal' files) there's no need for PathType.

**Comment by karimnaaji** [comment]
This seems like a nice change. No more headaches!

**Comment by tallytalwar** [comment]
This is good. Will clean this a bit and merge/squash to `url-scene-import` branch, to which this is based off.

**Comment by tallytalwar** [comment]
Cleaned this a bit and pushed these commits to `url-scene-import` PR.

**Pull request merged**
