### PR TITLE
benchmark on linux

### PR DESCRIPTION
**Pull request by hjanetzek**
rebased #214

### CODE REVIEW

**Comment by blair1618** [comment]
Oh I just commented on #214 that I'm in favor of merging when the conflicts are fixed - same here, we can just merge this one since it appears to be rebased.

**Comment by hjanetzek** [comment]
I'll look into - glm templates crashed gcc. probably just had a bad day (= 

https://travis-ci.org/tangrams/tangram-es/jobs/73509508#L1321

**Comment by blair1618** [comment]
Breaking compilers are we? :)

It's possible that GCC hit a memory limit and was killed by Travis, that's happened with `-j` before.

**Comment by hjanetzek** [comment]
@blair1618 yes, this is more likely..

**Comment by hjanetzek** [comment]
success!

**Pull request merged**
