### PR TITLE
Text/Sprite anchors

### PR DESCRIPTION
**Pull request by karimnaaji**
As in https://github.com/tangrams/tangram/pull/182

- [x] Add default justification relative to anchor

### CODE REVIEW

**Comment by hjanetzek** [comment]
Looks good to me!

**Comment by hjanetzek** [comment]
Could you squash 'Fix bouding boxes' into 'Comment...' ? to remove the merge conflict from history :)

**Comment by hjanetzek** [comment]
Just the scene should be set back to normal I guess. Then it's good to go!

**Comment by karimnaaji** [comment]
Oh yes will revert the scene!

**Pull request merged**
