### PR TITLE
Fix selection color applied to point labels

### PR DESCRIPTION
**Pull request by blair1618**
Resolves https://github.com/tangrams/tangram-es/issues/1167

This solves the observed problem, but I'm not sure that this is the intended data flow :\

### CODE REVIEW

**Comment by karimnaaji** [comment]
This actually breaks the unique selection color that each label would be broken. After some debugging I think I found where the issue lives.

Several things that makes this bug appear:
- On the issue https://github.com/tangrams/tangram-es/issues/1167, it is mentioned that the draw rule under the layer `layers.mz_current_location_gem.draw.ux-location-gem-overlay.interactive` is marked `interactive`, but it is actually not. I had to add that on my debugging code:
```c++
        std::vector<Tangram::SceneUpdate> updates = {
            {"layers.mz_current_location_gem.draw.ux-location-gem-overlay.interactive", "true"},
        };
        map->loadSceneAsync("https://raw.githubusercontent.com/tangrams/bubble-wrap/gh-pages/bubble-wrap.yaml",
            true, nullptr, nullptr, updates);
```
cc @ecgreb on that to confirm the value of the `interactive` flag.
- Some recent optimization uses the set `m_labels` within `labels.cpp` to retrieve the [label associated to a specific selection color](https://github.com/tangrams/tangram-es/blob/master/core/src/labels/labels.cpp#L67) read from the framebuffer. The bug is that this set is **only** added labels that can **not** occlude, which is true from the stylesheet [here](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L1159).

I guess the would be to have a separate vector in `labels.cpp` that contains all labels (including the ones that can't occlude) to be able to retrieve the matching selectionColor -> label.

**Comment by karimnaaji** [comment]
@blair1618 pushed on this branch https://github.com/tangrams/tangram-es/tree/hot-fix-1167.

**Comment by hjanetzek** [comment]
@karimnaaji  ah right! missing these interactive labels. We could add only the labels with selection color to m_selectionLabels instead of collecting all.

**Comment by karimnaaji** [comment]
@hjanetzek , right maintaining that set from `labels.cpp` would be the right way to handle that!

**Comment by blair1618** [comment]
Ah good catch, I forgot that each label needs it's own selection identifier and it can't just use the same one as the feature. I'll test that fix you pushed.

**Comment by tallytalwar** [comment]
@karimnaaji I see what you are mentioning.

1. Current location gem should be marked non interactive in the style sheet. It might be for the purposes of the example, @ecgreb could have referenced it. But yes I see the point of the bug :D.

2. I see the bug of non colliding labels are not checked when retrieving the labels for selection color. Instead of putting all visible labels for selection color checking, does it make sense to only put labels with "interactive" property set for selection color checking?

**Comment by ecgreb** [comment]
In the version of the stylesheet I was using at the time current location gem was marked interactive. However after [this commit](https://github.com/tangrams/bubble-wrap/commit/9738570b31b0d01746b0711082919ffca6c1d645#diff-b8806f7b52d569e5a54f86d92d7b4064L1095) was merged that is now no longer the case.

But yes I did verify the layer was interactive when reproducing the issue. And I agree the current location gem should NOT be interactive moving forward I was just using it for the test case.

**Comment by blair1618** [comment]
Yes, bubble-wrap was very recently revised to reduce the interactive layers.

Closing in favor of #1185

**Comment by nvkelso** [comment]
Some apps allow interactivity, we can modify our behavior to indicate say "current location" or "my location" on tap of the gem.

**Pull request closed without merging**
