### PR TITLE
Adding console arguments to RPI tangram

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
Hi there! this is the first attempt in a line of pulls to use tangram ES in a RaspberrPi to get thumbnails of tangram .yaml scenes. 

This pull essentially adds arguments to tangram so can load custom `scene` files, place (`lat`, `lon`, `zoom`) with specify `tilt` and `rotation` at a given `width` and `height`

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
After this is merge I'll speak to @blair1618 about the possibility of using https://github.com/nothings/stb/blob/master/stb_image_write.h to save the pixels on the frame buffer to an image (and add the arguments to make that possible)

**Comment by blair1618** [comment]
Looks like you committed old versions of the submodules for `alfons` and `geojson-vt-cpp`, let's remove those changes from the PR.

**Comment by patriciogonzalezvivo** [comment]
While you are there, Could you add this lines https://github.com/tangrams/paparazzi/blob/master/src/context.cpp#L46-L49

**Comment by blair1618** [comment]
Yep, added!

Can you give the code a try now and see if the continuous rendering is working as expected?

**Comment by patriciogonzalezvivo** [comment]
Working smoothly!

**Comment by patriciogonzalezvivo** [comment]
Hi! can we merge this to master? only affect rpi code

**Pull request merged**
