### PR TITLE
Ndk r10e

### PR DESCRIPTION
**Pull request by tallytalwar**
- Updated android.toolchain.cmake from the origin project head (https://github.com/taka-no-me/android-cmake)
- Updated android.toolchain.cmake to support ndk r10e.
- Remove the use of mindk.
-- Clone android-ndk from github android-ndk project as shown in a google-samples (github) project. Thanks @hjanetzek for the suggestion.

### CODE REVIEW

**Comment by tallytalwar** [comment]
Putting this on hold.

Will investigate on not using mindk at all, and directly using the default ndk from google's download link.

**Comment by hjanetzek** [comment]
maybe it's faster to fetch from the github server?
https://github.com/googlesamples/android-ndk/blob/master/.travis.yml

**Comment by tallytalwar** [comment]
@hjanetzek yes thats a good suggestion.

**Comment by tallytalwar** [comment]
I am going to merge this, if there are no concerns with this.

**Comment by blair1618** [comment]
Can you hold on for just a bit? I'm playing around with mindk and I want to evaluate build times

**Comment by tallytalwar** [comment]
:+1:

**Comment by tallytalwar** [comment]
Closing in favor of https://github.com/tangrams/tangram-es/pull/216

**Pull request closed without merging**
