### PR TITLE
Remove GLM submodule

### PR DESCRIPTION
**Pull request by matteblair**
We don't make changes to GLM, so there's not much value to maintaining it as a submodule -  copying in the files for the latest release is easier.

This also removes the GLM docs, which are over 10MB by themselves!

### CODE REVIEW

**Comment by hjanetzek** [comment]
Why not use git subtree to ease updating?

**Comment by lygstate** [comment]
He may means docs are hudge? but still prefre subtree.

**Comment by hjanetzek** [comment]
@lygstate yeah we also considered that - still undecided

**Comment by tallytalwar** [comment]
Looks like circle just broke on this. Will see if creating a new PR with the same commits fixes it.

**Pull request merged**
