### PR TITLE
avoid void* casting: move parseStyleParams to style subclasses

### PR DESCRIPTION
**Pull request by hjanetzek**
+ some c++11 specials for brief return type naming

### CODE REVIEW

**Comment by tallytalwar** [comment]
I have the same change done in sublayers branch. Will push in the evening when I get back home.

**Comment by hjanetzek** [comment]
ok, I stop tinkering with it :)

**Comment by tallytalwar** [comment]
Ohh @hjanetzek Not an issue.. Feel free to suggest stuff :D.

**Comment by hjanetzek** [comment]
obsolete now

**Pull request closed without merging**
