### PR TITLE
Text max lines option

### PR DESCRIPTION
**Pull request by hjanetzek**
Add support for `max_lines` text style option.

https://github.com/tangrams/tangram-es/issues/1543

shot-2017-07-06_17-34-47

### CODE REVIEW

**Comment by bcamper** [comment]
Looks good - however there shouldn't be a space between the last character
and the ellipsis - it looks like there may be one from the screenshot?

**Comment by hjanetzek** [comment]
Yes I can remove the 'allow-line-break' character when it's a space.

**Comment by hjanetzek** [comment]
shot-2017-07-06_18-10-39

**Comment by tallytalwar** [comment]
ellipsis with hindi:
screen shot 2017-07-10 at 12 24 26 pm

ellipsis with arabic/urdu:
screen shot 2017-07-10 at 12 55 38 pm
screen shot 2017-07-10 at 12 55 33 pm


Looks good to go. Merging.

**Pull request merged**
