### PR TITLE
Adjust visibility of marker points

### PR DESCRIPTION
**Pull request by karimnaaji**
#1057

### CODE REVIEW

**Comment by blair1618** [comment]
@karimnaaji Can you think of a way to do this without RTTI?

**Comment by blair1618** [comment]
Actually I'm gonna try something - hold on.

**Comment by karimnaaji** [comment]
What we can do is set a property in the mesh class `bool isLabelMesh()` or something in those lines, and `static_cast` on it. A lot of those casts are made in the codebase for this particular purpose, that would be good to remove it!

**Comment by blair1618** [comment]
Yeah, I'll do this with a separate change. 

It seems that the only RTTI we use in the core code is for checking style types and we can easily replace that with an enum member.

**Pull request merged**
