### PR TITLE
Offsets relative to local coordinate of line

### PR DESCRIPTION
**Pull request by karimnaaji**
For #310

### CODE REVIEW

**Comment by blair1618** [comment]
Looks perfect. @karimnaaji all good to merge?

**Comment by bcamper** [comment]
Is this relative to upright text direction (not strictly line direction)
like on JS? (Sorry on a phone, can't look mired closely.)

**Comment by karimnaaji** [comment]
@bcamper Not sure what upright text direction exactly means? But yes this is exactly the same ways as JS is currently implemented.

**Comment by blair1618** [comment]
Ooh so when the text flips to stay upright, the offset flips too?

**Comment by karimnaaji** [comment]
Yeah it does if you rotate

**Comment by bcamper** [comment]
Right text is always oriented upright. So as discussed previously, we will
need to add specific logic for rendering borders. cc @nvkelso

**Comment by blair1618** [comment]
Cool cool. We'll tackle the border issue in tandem with JS later on. This part seems to be ready to go.

**Comment by bcamper** [comment]
Yep

**Pull request merged**
