### PR TITLE
Url: remove duplicate slashes from path

### PR DESCRIPTION
**Pull request by hjanetzek**
Another option would be to change removeLastSegmentFromRange
to drop duplicate slashes

### CODE REVIEW

**Comment by blair1618** [comment]
Does this fix some undesirable behavior?

**Comment by hjanetzek** [comment]
yes - exemplified in the test case

**Comment by blair1618** [comment]
I'm not sure that this is the correct way to deal with duplicated slashes. I think that `//` represents a path segment containing an empty string and is distinct from no path segment. cURL seems to agree and resolves `file:///Users/matt/Downloads//../Desktop/little.txt` to `/Users/matt/Downloads/Desktop/little.txt`

**Comment by hjanetzek** [comment]
It might be shell user common sense but not part of url dots removal spec. Or an option for a nitpick PR on curl.

**Comment by blair1618** [comment]
Mmmmm I'm not convinced - NSURL and cURL both treat it as an empty path segment, and they are designed for handling generic URLs whereas bash/zsh is not.

**Comment by hjanetzek** [comment]
Yeah ok - it seems to be the rule for URLs to have `..` replace empty path segments

**Pull request closed without merging**
