### PR TITLE
Cleanup debug code

### PR DESCRIPTION
**Pull request by karimnaaji**
Cleanup debug code from `tangram.cpp` to make it easier to step through main interface.

### CODE REVIEW

**Comment by karimnaaji** [comment]
@tallytalwar , can you give a look to fix travis build on this, I can't figure out why linux build keeps failing and my linux setup is not yet usable.

**Comment by tallytalwar** [comment]
Sure, will check it out.

**Comment by tallytalwar** [comment]
Interesting that this works with clang-3.6 on linux.

**Comment by tallytalwar** [comment]
Will look more closely at whats happening in this PR, which is calling g++ to bomb!

**Comment by hjanetzek** [comment]
The problem is that gnu libc++ has its own debug/debug.h
How about debug/frameInfo and moving DebugFlags to tangram.h?

One thing: can we have clang-format ColumnLimit: 100?

**Comment by blair1618** [comment]
LGTM

**Comment by blair1618** [comment]
@hjanetzek I think the column limit in our .clang-format is 120 because it's roughly the width that can be viewed without scrolling in github. You prefer 100?

**Pull request merged**
