### PR TITLE
Fixes #843

### LINKED ISSUE #843: Visibility of dynamic point features is inconsistent on Android
https://gfycat.com/SourSadAndeancat

This produces no obviously relevant error output and can't be reproduced in the desktop demo.

### PR DESCRIPTION
**Pull request by tallytalwar**

### CODE REVIEW

**Comment by blair1618** [comment]
LGTM

Worth noting that while testing this, I discovered that #843 was _not_ reproducible on my Moto X, but was on my Galaxy S7.

**Comment by blair1618** [comment]
Can you revise this commit message to say something like "Fix uninitialized variables in Label and TileManager" and then merge?

**Comment by tallytalwar** [comment]
Thats good to know. We can still repro this on some devices. Will borrow your s7 tomorrow :D.

**Comment by tallytalwar** [comment]
Updated

**Comment by blair1618** [comment]
Awesome, merge when Travis is ready!

**Pull request merged**
