### PR TITLE
Add Javadoc generation

### PR DESCRIPTION
**Pull request by blair1618**
This was basically already present in a gradle script, mostly just needed some syntax revisions in our javadoc. 

This isn't a final revision on documentation, as the interfaces may still change before the SDK release.

### CODE REVIEW

**Comment by blair1618** [comment]
@hjanetzek take a look when you have a second. Thanks!

**Comment by tallytalwar** [comment]
This looks good to me. Of course we need to scan through all documentation to finalize everything for the release.

**Comment by karimnaaji** [comment]
Looks good to me too

**Comment by hjanetzek** [comment]
Looks good! 

Just noticed one thing: The Renderer implementation should be an inner class so its interface is not exposed in MapController

**Comment by blair1618** [comment]
@hjanetzek Good call. I'll take a look at that separately because I want to make sure it can still be usefully extended (e.g. to create a stereoscopic for a cardboard app).

**Pull request merged**
