### PR TITLE
Allow material colors to be specified as hex or css colors

### LINKED ISSUE #536: Material properties should allow color strings
https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L255

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/materials.md#material-properties

### PR DESCRIPTION
**Pull request by blair1618**
Resolves #536

### CODE REVIEW

**Comment by tallytalwar** [comment]
Is there an issue also for allowing css colors and #hex values for light colors?

**Comment by blair1618** [comment]
Ah, you're right - light colors have the same issue: https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L657-L665

I can fix this for light colors in this PR as well.

**Comment by blair1618** [comment]
@tallytalwar light colors also take string specifiers now!

**Comment by tallytalwar** [comment]
looks nice. merging.

**Pull request merged**
