### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by msmollin**
~~RIP Mapzen :(~~

(edit: varun) Linux Foundation ❤️ Mapzen!

### CODE REVIEW

**Comment by matteblair** [comment]
Long live Mapzen :)

**Comment by tallytalwar** [comment]
We should update licenses also. But LF!! :D

**Comment by tallytalwar** [comment]
We should update this further now? cc. @nvkelso on timing and words?

**Comment by nvkelso** [comment]
I think it's fine for now.

**Pull request merged**
