### PR TITLE
Force Android Ninja builds on CircleCI to only use 4 concurrent jobs

### PR DESCRIPTION
**Pull request by matteblair**

### CODE REVIEW

**Comment by hjanetzek** [comment]
LGTM

Just found that CMake 3.11 provides these options for more fine-tuning
```
-DCMAKE_JOB_POOL_COMPILE:STRING=compile
-DCMAKE_JOB_POOL_LINK:STRING=link
'-DCMAKE_JOB_POOLS:STRING=compile=5;link=2'
```
https://stackoverflow.com/questions/51557585/limit-cpu-cores-for-ndkbuild-with-cmake-and-ninja

**Comment by matteblair** [comment]
Still isn't limiting concurrency like we want. 

Changing the make program like I tried doesn't work because the make program variable is called within quotes, as if its a file name. 

The current version of CMake in the NDK is 3.6, so we can't use any features introduced later than that. I do see that CMake 3.6 has `JOB_POOLS` documented (https://cmake.org/cmake/help/v3.6/prop_gbl/JOB_POOLS.html) so that might still work, but it currently isn't. It might just not be entering the conditional block at all.

**Comment by matteblair** [comment]
By the way I'm testing this by SSHing into the CircleCI job and watching `top` during the native compile task. With the latest commit that supposedly limits the job pool to 4, I'm seeing things like this:
```
top - 16:58:44 up  8:28,  0 users,  load average: 10.32, 14.66, 12.68
Tasks: 116 total,  28 running,  88 sleeping,   0 stopped,   0 zombie
%Cpu(s): 40.3 us,  3.2 sy,  0.0 ni, 56.4 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 72037048 total,  7500312 free, 11943792 used, 52592944 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 58690684 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                
  988 circleci  20   0  169400 121876  37608 R  33.9  0.2   0:02.35 clang                                                                  
 1026 circleci  20   0  150120 103936  38316 R  32.6  0.1   0:01.41 clang++                                                                
 1085 circleci  20   0   90988  35984  26888 R  31.9  0.0   0:01.00 clang++                                                                
 1345 circleci  20   0  104476  58172  37520 R  12.6  0.1   0:00.38 clang++                                                                
 1320 circleci  20   0  105488  58924  37548 R  12.3  0.1   0:00.37 clang++                                                                
 1358 circleci  20   0  102380  49188  30968 R  10.0  0.1   0:00.30 clang++                                                                
 1362 circleci  20   0   98632  44156  28824 D   9.6  0.1   0:00.29 clang++                                                                
 1391 circleci  20   0  100468  45508  29132 D   9.6  0.1   0:00.29 clang++                                                                
 1319 circleci  20   0   98008  43164  28372 R   8.6  0.1   0:00.26 clang++                                                                
 1356 circleci  20   0   98936  44404  28924 D   8.6  0.1   0:00.26 clang++                                                                
 1376 circleci  20   0   98528  43660  28624 R   8.3  0.1   0:00.25 clang++                                                                
 1387 circleci  20   0   97700  42792  28336 R   8.3  0.1   0:00.25 clang++                                                                
 1352 circleci  20   0   98304  43484  28708 R   8.0  0.1   0:00.24 clang++                                                                
 1393 circleci  20   0   98308  43420  28608 R   8.0  0.1   0:00.24 clang++                                                                
 1364 circleci  20   0   97488  42700  28632 R   7.3  0.1   0:00.22 clang++                                                                
 1359 circleci  20   0   95380  40596  28292 R   7.0  0.1   0:00.21 clang++                                                                
 1397 circleci  20   0   95804  40960  28388 R   7.0  0.1   0:00.21 clang++                                                                
 1351 circleci  20   0   94284  39208  28448 D   6.3  0.1   0:00.19 clang++                                                                
 1395 circleci  20   0   94396  39348  28320 R   6.0  0.1   0:00.18 clang++                                                                
 1331 circleci  20   0   94236  39012  28252 D   5.6  0.1   0:00.17 clang++                                                                
 1350 circleci  20   0   94088  38952  28380 R   5.6  0.1   0:00.17 clang++                                                                
 1380 circleci  20   0   93368  38388  28372 R   5.3  0.1   0:00.16 clang++                                                                
 1357 circleci  20   0   93688  38608  28540 R   5.0  0.1   0:00.15 clang++                                                                
 1405 circleci  20   0   93520  38448  28416 R   4.3  0.1   0:00.13 clang++                                                                
 1366 circleci  20   0   91524  36608  28388 R   3.7  0.1   0:00.11 clang++                                                                
  541 circleci  20   0 14.639g 1.023g  28544 S   3.3  1.5   1:00.83 java                                                                   
 1400 circleci  20   0   89644  34576  28132 R   2.7  0.0   0:00.08 clang++                                                                
  869 circleci  20   0   15604   5176   2952 R   2.0  0.0   0:00.10 ninja                                                                  
 1410 circleci  20   0   88236  33136  27992 R   1.7  0.0   0:00.05 clang++                                                                
 1423 circleci  20   0   87620  32572  27640 D   1.7  0.0   0:00.05 clang++
```

**Comment by matteblair** [comment]
I think this is actually working now!! 🎉 

Job pools for the Ninja generator, like @hjanetzek suggested, are the only thing that seems to work for this. The change to the build configuration is very localized and readable and the build times don't seem noticeably slower with "compile pool" of 4 jobs and a "link pool" of 2 jobs.

**Pull request merged**
