### PR TITLE
[exp/rfc] libyaml2yaml-cpp

### PR DESCRIPTION
**Pull request by hjanetzek**
Just quick testing how much one could gain from making yaml-cpp parsing faster (`load`). Initial results show 3x speedup on Z3.

```
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:64: --------load 379.700012
....
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:72: --------fonts 313.782013
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:167: --------apply globals 237.731995
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:193: -------- textures 1.678000
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:228: -------- styles 58.745998
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:253: -------- layers  1222.076050
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:299: --------build styles 27.680000
W/Tangram ( 5807): TANGRAM sceneLoader.cpp:78: --------apply 1570.739014
W/Tangram ( 5807): TANGRAM tangramapp.cpp:40: DRAW GL
W/Tangram ( 5807): TANGRAM styleContext.cpp:173: --------js globals: 27.313000
W/Tangram ( 5807): TANGRAM styleContext.cpp:179: --------js functions: 32.349003
...
W/Tangram ( 5807): TANGRAM tangram.cpp:415: --------shaders 1018.005005
```
vs previously 
```
 W/Tangram (17625): TANGRAM sceneLoader.cpp:62: --------load 1232.239014
....
W/Tangram (17625): TANGRAM sceneLoader.cpp:70: --------fonts 323.578003
W/Tangram (17625): TANGRAM sceneLoader.cpp:165: --------apply globals 322.205017
W/Tangram (17625): TANGRAM sceneLoader.cpp:191: -------- textures 1.800000
W/Tangram (17625): TANGRAM sceneLoader.cpp:226: -------- styles 76.507004
W/Tangram (17625): TANGRAM sceneLoader.cpp:251: -------- layers  1261.566040
W/Tangram (17625): TANGRAM sceneLoader.cpp:297: --------build styles 26.702999
W/Tangram (17625): TANGRAM sceneLoader.cpp:76: --------apply 1710.754028
....
W/Tangram (17625): TANGRAM tangram.cpp:413: --------shaders 957.579956
```
(also added some more changes to yaml-cpp which probably made 'apply' and 'applyGlobals' faster)

Using rapidjson data structures   is the better approach in the end though. 
Depending on how long it takes to do the full switch we could consider using this PR for now.

Update:
```
W/Tangram (27837): TANGRAM sceneLoader.cpp:62: --------load 381.438995
...
W/Tangram (27837): TANGRAM sceneLoader.cpp:70: --------fonts 311.890015
...
W/Tangram (27837): TANGRAM sceneLoader.cpp:204: --------apply globals 157.806000
W/Tangram (27837): TANGRAM sceneLoader.cpp:230: -------- textures 314.911011
W/Tangram (27837): TANGRAM sceneLoader.cpp:265: -------- styles 38.757999
W/Tangram (27837): TANGRAM sceneLoader.cpp:290: -------- layers  443.756012
W/Tangram (27837): TANGRAM sceneLoader.cpp:336: --------build styles 26.427999
W/Tangram (27837): TANGRAM sceneLoader.cpp:76: --------apply 1005.797974 (sum applyConfig)
...
W/Tangram (27837): TANGRAM tangram.cpp:414: --------shader: 65.430000 - building-grid
W/Tangram (27837): TANGRAM tangram.cpp:418: --------shaders 1031.916992 / 1042.235962
```
Textures were not loaded before so applyConfig went down by 1 second overall since the beginning. `layers` got most of the speedup from the getDouble changes - we checked all filter values for numbers first which allocates a stringstream for decoding.

Shaders look like the next promising optimization (this part takes 2 seconds on my HTC m7).

### CODE REVIEW

**Comment by blair1618** [comment]
Wow! I would've expected that yaml-cpp would already parse as efficiently as possible for its own data structures, but clearly that's not the case. 

As you said, using rapidjson data structures will be worth the effort since they are more compact in memory and should speed up all parts of loading. However if this approach works robustly for all of our current scene files, it might be a nice incremental improvement.

**Comment by hjanetzek** [comment]
Yes, the parser and self-made regex code of yaml-cpp are painfully of slow.. looks not too hard to optimize though - if I had some spare time.

**Comment by tallytalwar** [comment]
Probably irrelevant now, since we have yaml-cpp optimized and y2j happening!

**Comment by hjanetzek** [comment]
yep, and yaml-cpp parser is now as fast as libyamls :)

**Pull request closed without merging**
