### PR TITLE
0.6.2 patch

### PR DESCRIPTION
**Pull request by matteblair**
Do not merge this PR!

This is the set of cherry-picked commits that will go into the 0.6.2 patch release. The patch release will be made from a dead-end branch, since `master` now includes changes that we do not intend to release before 0.7.0.

### CODE REVIEW

**Comment by tallytalwar** [comment]
We should have a PR for 6c64cf5bbdf339c56d9229ac1a81684c7c756e5b to go in master also.

**Comment by westnordost** [comment]
Is it planned to release 0.6.2 this week? I am be able to immediately release a new SC version when the patch is out

On 27 April 2017 03:25:47 CEST, Varun <notifications@github.com> wrote:
>We should have a PR for 6c64cf5bbdf339c56d9229ac1a81684c7c756e5b to go
>in master also.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tangrams/tangram-es/pull/1475#issuecomment-297585590

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matteblair** [comment]
@westnordost The 0.6.2 release was just tagged and deployed to Maven central, it should be available from Maven in a matter of hours.

**Comment by matteblair** [comment]
Also github is displaying these commits in the wrong order due to moving things around in history - the "Release 0.6.2" commit is last, as one would expect.

**Comment by matteblair** [comment]
This has been released and merged with `master`, closing the PR.

**Comment by westnordost** [comment]
Thank you, guys :-)
I just deployed the new SC version, hopefully it makes the Android 4.x people happy

**Pull request closed without merging**
