### PR TITLE
0.5.2 ios

### PR DESCRIPTION
**Pull request by hjanetzek**
@tallytalwar if you have a chance to do a world trip on this branch I would be curious about the memory usage compared to 0.5.1 :)

### CODE REVIEW

**Comment by tallytalwar** [comment]
@hjanetzek you might also want to include the fixes for marker visibility (old ones already in master) or maybe your recent PR here.

**Comment by hjanetzek** [comment]
@tallytalwar feel free to pick the needed commits - I cannot test here. We can sort the commits later

**Comment by matteblair** [comment]
I'm rearranging these commits for a release now, hang tight!

**Comment by tallytalwar** [comment]
And for documentation purposes (outside slack):
We see a memory usage improvement from 0.5.1 by about 56MB.

**Comment by matteblair** [comment]
This was released here: https://github.com/tangrams/tangram-es/releases/tag/0.5.2

From this branch: https://github.com/tangrams/tangram-es/tree/0.5.2-patch

**Pull request closed without merging**
