### PR TITLE
Adding density parameter to Marker.setBitmap.

### PR DESCRIPTION
**Pull request by polar**
This pull requests addresses the following issue: https://github.com/tangrams/tangram-es/issues/1925 
Previously, bitmaps were not transferred to the Texture object with a density parameter, which lead to scaled up bitmaps on the map when the device density is higher than 1.

### CODE REVIEW

**Comment by polar** [comment]
I kind of new that this PR would break the iOS build. I haven't set up a Mac to try it out yet, and I'm not too familiar with the iPhone since a few years ago. It looks like TGMarker.mm needs to add a density parameter to `tangramInstance.setMarkerBitmap(...., density);`  
I am unclear of what `density` should be. Should it be `UIScreen.scale`?

**Comment by matteblair** [comment]
I can check out the iOS implementation and see how to make that match. 

For the Android changes, I'm now setting up a repro case to verify that the changes fix what we expect. @polar How were you creating the BitmapDrawables that ended up with the wrong size?

**Comment by polar** [comment]
@matteblair Yes, I was creating the BitmapDrawables.

**Comment by polar** [comment]
I just tried it, and sadly the density is not fixed.

**Comment by matteblair** [comment]
Hey sorry, I dropped the ball on this PR - didn't want to delay the already-late release :\

I'll take another run at this to figure out the root issue and I expect we'll be able to put the change in a patch release - it shouldn't be a breaking change.

**Comment by matteblair** [comment]
Hey thanks again for finding the cause of this issue, the fix should be applied in https://github.com/tangrams/tangram-es/pull/1976, let me know if you see other problems!

**Pull request closed without merging**
