### PR TITLE
Find fallback fonts on pre Lollipop Android versions

### PR DESCRIPTION
**Pull request by hjanetzek**
This PR adds sans-serif and no-name font family groups to the list of fallback fonts.

### CODE REVIEW

**Comment by tallytalwar** [comment]
I will give one of the phones in the stock here a try.

**Comment by tallytalwar** [comment]
The S3 we have running 4.0.4 has the following:

```
shell@android:/ $ ls -l /system/etc/fallback_fonts.xml                                                <
-rw-r--r-- root     root         4031 2012-05-23 10:23 fallback_fonts.xml
shell@android:/ $ ls -l /etc/fallback_fonts.xml
-rw-r--r-- root     root         4031 2012-05-23 10:23 fallback_fonts.xml

shell@android:/ $ ls -l /system/etc/system_fonts.xml
-rw-r--r-- root     root         2595 2012-05-23 10:23 system_fonts.xml
shell@android:/ $ ls -l /etc/system_fonts.xml
-rw-r--r-- root     root         2595 2012-05-23 10:23 system_fonts.xml
```

I see that you changed the paths here. Any reason for that?

**Comment by tallytalwar** [comment]
Other than the above question .. renders look good wrt all fallback fonts.

**Comment by hjanetzek** [comment]
@tallytalwar it's the path that is stated in '/system/etc/system_fonts.xml' comments. Also we use `/system/` prefix for post lollipop path. So just consistency.

@matteblair you can download older Android emulator images in AVD with a few clicks when creating a new device.

**Comment by tallytalwar** [comment]
Thanks @hjanetzek, makes sense. Good to go.

**Comment by matteblair** [comment]
This was merged into `master` in the 0.6.2 patch (d0a66e7037b7c9a5de663e188fcb5aaff83b03f1)

**Pull request closed without merging**
