### PR TITLE
fix: consistent sorting of label pairs

### PR DESCRIPTION
**Pull request by hjanetzek**
- also on tizen this crashed for optimized builds previously

### CODE REVIEW

**Comment by karimnaaji** [comment]
@hjanetzek what was the crash on this code?

**Comment by hjanetzek** [comment]
@karimnaaji I haven't stepped through all the data - I guess the gcc 4.9 sort implementation is picky for strict weak ordering http://stackoverflow.com/questions/16824667/doesnt-stl-sort-require-a-strict-weak-ordering-to-work. The partition subroutine went reproducably out of bounds

**Comment by karimnaaji** [comment]
@hjanetzek Did you actually want a merge commit in this one?

**Comment by hjanetzek** [comment]
@karimnaaji I would say squash'n'merge

**Pull request merged**
