### PR TITLE
Sub layer fixes

### PR DESCRIPTION
**Pull request by tallytalwar**
Minor but critical fixes to subLayers.
This branch is based on "concrete-filter" should be merged post that.

### CODE REVIEW

**Comment by tallytalwar** [comment]
Yes in the BFS traversal for Style:: applyLayerFiltering.

**Comment by blair1618** [comment]
Raw pointers could be safely used there regardless, no allocation or deletion is happening. 

I also try to avoid type aliases. Naming is one of the two hardest problems in computing, so if we can avoid doing it, why not? :)

**Comment by tallytalwar** [comment]
I reverted the last commit.

and yes shared_ptr are needed for SceneLayer since, multiple raw groups can share these layers.

**Comment by tallytalwar** [comment]
#199 PR.

**Pull request merged**
