### PR TITLE
Sprites

### PR DESCRIPTION
**Pull request by karimnaaji**
Introduction of sprites for icons.

This PR has two dependencies #172, #182.
It introduces sprite atlases (only hard-coded for now but will have to parse it like [here](https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L29_L47)), and split label class into sprite-label/text-label, to have state management (fading in/out), and usage of the collision-detection system.

~~TODO after #172 and #182 gets merged: fix bounding boxes.~~

### CODE REVIEW

**Comment by blair1618** [comment]
Reviewing now! 

Are the sprites here supposed to be updating their positions?

**Comment by karimnaaji** [comment]
Yes they should but only with the dependent features (#182 #172). Maybe it'd be better to review dynamic meshes first and then I'll merge all the dependencies in this branch for review, and sprites will update :)

**Comment by blair1618** [comment]
I see, yeah it's a bit weird to review the other branches based on this when I haven't seen everything in this branch, but it probably makes sense to merge those first.

**Comment by karimnaaji** [comment]
Closing in favor of #196

**Pull request closed without merging**
