### PR TITLE
Use a proper dead states for discarded labels

### PR DESCRIPTION
**Pull request by karimnaaji**
When occlusion happens to a label that has been in a visible state at least once, mark this label as a label that could go out of the sleeping state.

label-states

This adds some issues, like flickering or cascading fading when more occlusion happens at the same time. To solve that, we would need to consolidate a little bit on which state would be marked as an "occluding" state.

### CODE REVIEW

**Comment by karimnaaji** [comment]
This would also improve determinism when combined with proper priorities.

**Comment by hjanetzek** [comment]
@karimnaaji Any objections to merge this now?

**Comment by tallytalwar** [comment]
We were holding this. He did not want to merge this... I dont remember the reason why!!!

**Comment by karimnaaji** [comment]
I wanted to profile this first :/ I don't think it's safe to merge without adding some more thoughts on it, it'll probably drop down the framerate at some zoom levels where label density is really high..

**Comment by hjanetzek** [comment]
Make sure to test in Release mode. It made a huge impact last time I tried the isect2d demo

**Comment by hjanetzek** [comment]
To avoid per frame allocations for intersection pairs in isect2d::intersect it is probably beneficial to have a reusable instance for its temporary data

**Comment by tallytalwar** [comment]
@karimnaaji  (I can officially tag you now :D). Can you update this? Was your main concern performance?

@hjanetzek made isect2d more fast, than what we had so this should be much better now. So this should be good to merge?

**Comment by karimnaaji** [comment]
I checked the isect2d changes, it looks really good to me now.  It must be good to merge. We can follow up on this to improve some subtile flickering I noticed later.

**Pull request merged**
