### PR TITLE
Logs

### PR DESCRIPTION
**Pull request by karimnaaji**
Provide a way to reduce locally defined macro and log level. If needed we could provide a hand to the user on this log level directly on the library.

### CODE REVIEW

**Comment by tallytalwar** [comment]
Good to go.

**Comment by tallytalwar** [comment]
Getting a bunch of warning on LOG... 

```
warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
```

cc @hjanetzek, were you not getting these in another branch?

**Comment by hjanetzek** [comment]
@tallytalwar, cherrypick this one https://github.com/tangrams/tangram-es/commit/471bda1e4d0db9c00a5a14adcfde9b5ac90701c2

**Comment by hjanetzek** [comment]
Please put this on hold until sceneloader refactoring is merged.

**Comment by tallytalwar** [comment]
@hjanetzek sure.

**Comment by tallytalwar** [comment]
Going to merge this.

**Pull request merged**
