### PR TITLE
Style setup refactor

### PR DESCRIPTION
**Pull request by blair1618**
Splits style setup into a per-frame setup and a per-tile setup (which are implemented as no-ops in the base style class)

### CODE REVIEW

**Comment by blair1618** [comment]
@karimnaaji @tallytalwar Does this make sense?

**Comment by karimnaaji** [comment]
Yes definitely!

**Comment by tallytalwar** [comment]
Yes, looks good.

**Comment by blair1618** [comment]
Travis is failing on ndk extraction but I just tested on Android and all seems well

**Pull request merged**
