### PR TITLE
Merged sprites

### PR DESCRIPTION
**Pull request by hjanetzek**
git show a78c5e15 (or git diff-tree --cc a78c5e15) helps to spot which parts were touched during conflict resolution

### CODE REVIEW

**Comment by tallytalwar** [comment]
This looks good to be merged.

**Comment by karimnaaji** [comment]
Yep, no more changes in process!

**Comment by hjanetzek** [comment]
:+1: closing the week of the big merges on time

**Comment by blair1618** [comment]
:clap:

**Pull request merged**
